
CREATE DATABASE auth_db;
CREATE DATABASE attendance_db;
CREATE DATABASE payroll_db;

GRANT ALL PRIVILEGES ON DATABASE auth_db TO CURRENT_USER;
GRANT ALL PRIVILEGES ON DATABASE attendance_db TO CURRENT_USER;
GRANT ALL PRIVILEGES ON DATABASE payroll_db TO CURRENT_USER;
